#!/usr/bin/env bash
# Build the WCIM 2026 e-poster PDF.
#
#   ./build.sh                       # use the bundled vector letterhead
#   ./build.sh path/to/template.png  # use the official WCIM template artwork
#
# Output: eposter.pdf (A4 portrait, 1 page, PDF).
set -euo pipefail
cd "$(dirname "$0")"

OVERRIDE="assets/bg-override.css"

if [[ $# -ge 1 ]]; then
  src="$1"
  [[ -f "$src" ]] || { echo "template not found: $src" >&2; exit 1; }
  ext="${src##*.}"
  cp "$src" "assets/wcim-template.${ext}"
  cat > "$OVERRIDE" <<CSS
/* generated by build.sh — official template artwork */
.page { background-image: url("wcim-template.${ext}") !important; }
CSS
  echo "background: assets/wcim-template.${ext} (official template)"
else
  rm -f "$OVERRIDE"
  echo "background: assets/wcim-bg.svg (vector reconstruction)"
fi

node render.mjs
echo
echo "--- checks ---"
python3 - <<'PY'
import re
d = open('eposter.pdf', 'rb').read()
mb = re.search(rb'/MediaBox\s*\[([^\]]+)\]', d).group(1).split()
w, h = (float(mb[2]) * 25.4 / 72, float(mb[3]) * 25.4 / 72)
pages = len(re.findall(rb'/Type\s*/Page[^s]', d))
fonts = sorted({f.decode() for f in re.findall(rb'/BaseFont\s*/([A-Za-z0-9+#\-,]+)', d)})
print(f"size   {len(d)/1024:7.0f} KB   {'OK' if len(d) <= 5*1024*1024 else 'OVER 5 MB'}")
print(f"pages  {pages:7d}      {'OK' if pages == 1 else 'MUST BE 1'}")
print(f"page   {w:.0f} x {h:.0f} mm  {'OK (A4)' if abs(w-210) < 1 and abs(h-297) < 1 else 'NOT A4'}")
print(f"fonts  {', '.join(fonts)}")
PY
